<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>contexts</key>
	<dict>
		<key>brackets</key>
		<array>
			<dict>
				<key>match</key>
				<string>\]</string>
				<key>pop</key>
				<true/>
			</dict>
			<dict>
				<key>include</key>
				<string>main</string>
			</dict>
		</array>
		<key>main</key>
		<array>
			<dict>
				<key>match</key>
				<string>\[</string>
				<key>push</key>
				<string>brackets</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\]</string>
				<key>scope</key>
				<string>invalid.illegal.stray-bracket-end</string>
			</dict>
		</array>
	</dict>
	<key>fileTypes</key>
	<array>
		<string>ss</string>
		<string>cd</string>
		<string>Candy</string>
	</array>
	<key>name</key>
	<string>Candy</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Tab stops like $1, $2...</string>
			<key>match</key>
			<string>\#\d+</string>
			<key>name</key>
			<string>keyword.other.open_swift</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Tab stops like $1, $2...</string>
			<key>match</key>
			<string>class|extends|var|function|callback</string>
			<key>name</key>
			<string>keyword.aaa.open_swift</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.open_swift</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.from.open_swift</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?:(import)|(from))\b</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keywords that delimit flow blocks or alter flow from within a block</string>
			<key>match</key>
			<string>\b(else|for|if|while|break|continue|return)\b</string>
			<key>name</key>
			<string>keyword.control.flow.open_swift</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|in|is|not|or|as)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.open_swift</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.open_swift</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.open_swift</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(this|self).?\b</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#docstrings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#json2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.open_swift</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.open_swift</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.open_swift</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=//)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.open_swift</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>//</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.open_swift</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.double-slash.open_swift</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>(?&gt;\\\s*\n)</string>
									<key>name</key>
									<string>punctuation.separator.continuation.open_swift</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>docstrings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(''')</string>
					<key>contentName</key>
					<string>string.quoted.triple.open_swift</string>
					<key>end</key>
					<string>(''')</string>
					<key>name</key>
					<string>string.interpolated.open_swift</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(""")</string>
					<key>contentName</key>
					<string>string.quoted.triple.open_swift</string>
					<key>end</key>
					<string>(""")</string>
					<key>name</key>
					<string>string.interpolated.open_swift</string>
				</dict>
			</array>
		</dict>
		<key>json</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>storage.type.open_swift</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>storage.type.open_swift</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(\?[?:[:=!&gt;]|&lt;[=!]])</string>
							<key>name</key>
							<string>support.function.assertion.escapedregexp</string>
						</dict>
						<dict>
							<key>match</key>
							<string>([:,'"\[\]])</string>
							<key>name</key>
							<string>keyword.other.open_swift</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>json1</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.open_swift</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>XXX: Implement named groups, options and yes/no groups.</string>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.open_swift</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.other.attribute-name.open_swift</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\?(?:[:=!&gt;]|&lt;[=!]))</string>
					<key>name</key>
					<string>support.function.assertion.escapedregexp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([+-]?\d+.?\d*)</string>
					<key>name</key>
					<string>constant.numeric.open_swift</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(")</string>
					<key>contentName</key>
					<string>string.quoted.double.open_swift</string>
					<key>end</key>
					<string>(")</string>
					<key>name</key>
					<string>string.interpolated.open_swift</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(')</string>
					<key>contentName</key>
					<string>string.quoted.double.open_swift</string>
					<key>end</key>
					<string>(')</string>
					<key>name</key>
					<string>string.interpolated.open_swift</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.open_swift</string>
	<key>uuid</key>
	<string>91f295c9-96e5-427b-9387-85c648effe6f</string>
</dict>
</plist>
